name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."
  PUBLIC_GA_MEASUREMENT_ID: G-CK1NLPG2EQ
  PUBLIC_CWA_BEACON_TOKEN: 279d2ec248754a7cb0f31f3c760d0b7d
  PUBLIC_GISCUS_REPO: tsirif/tsirif.github.io
  PUBLIC_GISCUS_REPO_ID: R_kgDOQFjsYw
  PUBLIC_GISCUS_CATEGORY: General
  PUBLIC_GISCUS_CATEGORY_ID: DIC_kwDOQFjsY84Cw3q7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v4
        with:
          path: .                # root of the Astro project
          node-version: 22       # Node version for the build
          package-manager: pnpm@latest  # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
          build-cmd: pnpm run build  # build command for the Astro project
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
